version: '3.7'

services:

  dnn_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '5000:5000'
    expose:
        - '5000'
    depends_on:
      - tensorflow_service
    restart: unless-stopped

  tensorflow_service:
    image: tensorflow/serving:2.4.0
    container_name: tensorflow_service
    command: --port=8500 --rest_api_port=8501 --model_name=dnn --model_base_path=/models/dnn
    volumes:
      - ./dnn:/models/dnn
    restart: unless-stopped
    